Customer collection
interglobalvision/globie-final-boss pull request #14
Opened 2017-04-17 23:57 UTC by mikeyrayvon

- customer collection
- typeahead existing customers list
- customer method

2017-04-18 22:32 UTC, varffs requested changes
This is basically all good. However to associate the data just with a string not an ID style string I think is a bad pattern. The project should save the name of the customer but also the customer ID to make relational queries cleaner.

2017-04-18 22:32 UTC, varffs commented on app/imports/components/projects/AddProject.jsx
> +    setTimeout(function() {
these should be set to a specific timer and reset on focus if possible. Otherwise possible to stack a bunch of timeouts

2017-04-18 22:32 UTC, varffs commented on app/imports/components/projects/AddProject.jsx
> +        this.cleanForm();
this should take you to either the single route for the created project or the list of projects

2017-04-18 23:01 UTC, mixcas commented on app/imports/components/projects/AddProject.jsx
> +        this.cleanForm();
It will re route to single project view but it is not ready, so i think it's ok like this for now.

2017-04-19 00:36 UTC, mixcas commented on app/imports/components/projects/AddProject.jsx
> +        <li className='pt-menu-item' onClick={this.onCustomerClick}>{customer.entry.name}</li>
This is wrong, DOM doesn't go into `state` ever. Data is the only thing that goes into `state`. DOM goes exclusively in `render()`.

2017-04-20 17:41 UTC, mikeyrayvon commented on app/imports/components/projects/AddProject.jsx
> +    setTimeout(function() {
whats a specific timer?

2017-04-20 18:00 UTC, mikeyrayvon commented on app/imports/components/projects/AddProject.jsx
> +    setTimeout(function() {
nvm i guess i figured out what u mean

2017-04-24 19:10 UTC, mikeyrayvon commented
i think this is good to go, no?

2017-04-24 22:30 UTC, varffs commented
Branch won't work for me. I get a validation error `Customer id is required` with both new customers and existing ones

2017-04-25 00:25 UTC, mixcas commented
@varffs is any the tests failing?

2017-04-25 18:25 UTC, varffs requested changes

2017-04-25 18:25 UTC, varffs commented on app/imports/components/projects/AddProject.jsx
> +            this.validateProject();
this is good and all works. but i wonder if the function `validateProject` should at least be renamed to validateAndAddProject? Or if there is a way that there could be a submitForm function that calls validate and checks it's return before running the addCustomer logic?

2017-04-25 19:28 UTC, mixcas commented on app/imports/components/projects/AddProject.jsx
> +            this.validateProject();
My idea was to move the part that adds the Customer into a server only function that gets called inside the method. I was thinking theres no need to run this process of adding a new customer in the front end in this case. 

Not sure about this, I need to check the code to be sure of what i'm proposing.

2017-05-11 22:45 UTC, mikeyrayvon commented
pretty sure this is good to merge...

2017-05-12 10:32 UTC, varffs commented
no @mixcas needs to have a final check over of all changes but esp: https://github.com/interglobalvision/globie-final-boss/pull/14#discussion_r113288036

2017-05-15 14:04 UTC, mixcas commented
kk, im on it

2017-06-15 17:24 UTC, mikeyrayvon commented on app/imports/api/customersMethods.js
> +  validate:  CustomerSchema.validator(),
2 spaces

2022-04-25 07:47 UTC, closed without merging