Add admin dash
interglobalvision/globie-final-boss pull request #8
Opened 2017-03-15 00:37 UTC by mikeyrayvon

2017-03-17 23:21 UTC, varffs reviewed
Works well. Just a few general questions and possible some additional work on styling/layout

2017-03-17 23:21 UTC, varffs commented on app/imports/api/usersMethods.js
> +      Meteor.users.remove(workerId);
I think the method should return this not just invoke it. But perhaps doesnt matter

2017-03-17 23:21 UTC, varffs commented on app/imports/components/workers/AddWorker.jsx
> +      this.validate(worker);
how does `validate()` know what is it validating against?

2017-03-17 23:21 UTC, varffs commented on app/imports/components/workers/AddWorker.jsx
> +          console.log('success');
do we need this log?

2017-03-17 23:21 UTC, varffs commented on app/imports/components/workers/AddWorker.jsx
> +            <h2>Add Worker</h2>
I think we should add some basic paddings/margins to the layouts

2017-03-17 23:21 UTC, varffs commented on app/imports/components/workers/RemoveWorker.jsx
> +      <button className="pt-button pt-large" onClick={this.onRemoveWorker}>
I feel like this button needn't be large, but we just need a convention across the code

2017-03-17 23:21 UTC, varffs commented on app/imports/containers/ListWorkersContainer.jsx
> +    if (Roles.userIsInRole(user._id, [ 'admin' ])) {
not sure we need the double check as the subscription is already checked

2017-03-17 23:21 UTC, varffs commented on app/imports/startup/server/publications.jsx
> +  if (Roles.userIsInRole(this.userId, 'admin')) {
this raises the question of if we should lock down all subscriptions to users/roles. Probably so and therefor the projects list subscription needs that added

2017-03-17 23:24 UTC, varffs requested changes
When doing the update from master I realised the big question of where this dashboard goes

2017-03-17 23:24 UTC, varffs commented on app/imports/components/dashboards/MainDashboard.jsx
> +        <ListWorkersContainer />
Oh but either this needs to be conditionally shown according to user role or put in its own route which is admin user only. I would vote for own route

2017-03-20 19:12 UTC, mixcas commented on app/imports/api/usersMethods.js
> +      Meteor.users.remove(workerId);
I think `Method.Error` already gets back to the caller function.

> If you want to return an error from a method, throw an exception. Methods can throw any kind of exception. But Meteor.Error is the only kind of error that a server will send to the client.

2017-03-20 19:32 UTC, mixcas commented on app/imports/containers/ListWorkersContainer.jsx
> +    if (Roles.userIsInRole(user._id, [ 'admin' ])) {
true

2017-03-20 19:33 UTC, mixcas commented on app/imports/components/workers/AddWorker.jsx
> +      this.validate(worker);
Defined in line 73

2017-03-20 19:42 UTC, mixcas commented on app/imports/api/usersMethods.js
> +      Meteor.users.remove(workerId);
Actually maybe use this http://smashingthingstogether.com/handling-errors-in-meteor-methods/#the-wrapper-function:a41366158d30f9a95269470fa2f88962

2017-03-24 19:45 UTC, varffs commented
As discussed offline actions to take are:

- refine role related conditionals
- add basic layout margins
- move to admin role only route

2017-03-24 20:55 UTC, varffs approved these changes

2017-03-27 23:00 UTC, merged